### ISSUE TITLE
Dashboard does not work with latest flask (3.0.0)

### ISSUE THREAD

**Issue by harmenwassenaar** [sybrenjansen/mpire#106]
```
----> 1 from mpire.dashboard.dashboard import connect_to_dashboard, start_dashboard

~/Projects/mpire/mpire/dashboard/dashboard.py in <module>
      9 from typing import Dict, Optional, Sequence, Union
     10 
---> 11 from flask import escape, Flask, jsonify, render_template, request
     12 from werkzeug.serving import make_server
     13 

ImportError: cannot import name 'escape' from 'flask' (~/Projects/mpire/venv/lib64/python3.11/site-packages/flask/__init__.py)
```

**Comment by harmenwassenaar** [comment]
Apparently importing `escape` from flask was deprecated, and has now been removed. Importing it from markupsafe fixes it, and should be compatible with earlier versions as well.

**Comment by NiceBenn** [comment]
i have solved this problem by importing if from markupsafe , really thank you
